---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: auditHistory-API-test

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions: []
